# -*- coding: utf-8 -*-
"""Extract_Abstract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FBDntZmqprRSXNcknI7_2JCElvHHCOy_
"""

import aiohttp
import asyncio
import json
from bs4 import BeautifulSoup
from tqdm.asyncio import tqdm

# Function to extract abstract and title from URL asynchronously
async def extract_data_from_url(session, url):
    try:
        async with session.get(url) as response:
            html = await response.text()
            soup = BeautifulSoup(html, 'html.parser')
            abstract_section = soup.find('div', class_='abstract-content')
            abstract = abstract_section.get_text(separator='\n').strip() if abstract_section else "Abstract not available"
            title_tag = soup.find('title')
            title = title_tag.text if title_tag else "Title not found"
            return title, abstract
    except aiohttp.ClientConnectorError:
        return "Connection Error", ""
    except aiohttp.ServerDisconnectedError:
        return "Server Disconnected Error", ""

# Load Yesno_11.json file
with open('../Yesno_golden_merged.json', 'r', encoding='utf-8') as json_file:
    data = json.load(json_file)

# Load BioASQ_11B_test_yesno.json file if it exists
try:
    with open('Retrieved_golden_merged.json', 'r', encoding='utf-8') as retrieved_file:
        retrieved_data = json.load(retrieved_file)
except FileNotFoundError:
    retrieved_data = []

# Initialize set to store retrieved URLs
retrieved_urls = set(entry['url'] for entry in retrieved_data)

async def main():
    async with aiohttp.ClientSession() as session:
        for question in tqdm(data, desc="Processing documents"):
            document_urls = question['documents']
            tasks = []
            for url in document_urls:
                if url not in retrieved_urls:  # Check if URL is not retrieved yet
                    tasks.append(extract_data_from_url(session, url))
            results = await asyncio.gather(*tasks)
            for url, (title, abstract) in zip(document_urls, results):
                if url not in retrieved_urls:  # Check if URL is not retrieved yet
                    retrieved_data.append({
                        'url': url,
                        'title': title,
                        'abstract': abstract
                    })
                    retrieved_urls.add(url)


# Get the event loop
loop = asyncio.get_event_loop()

# Run the asynchronous main function
await main()

# Save retrieved data to BioASQ_11B_test_yesno.json file
with open('BioASQ_11B_test_yesno.json', 'w', encoding='utf-8') as output_file:
    json.dump(retrieved_data, output_file, indent=4, ensure_ascii=False)

print("Retrieved data saved to BioASQ_11B_test_yesno.json")

import aiohttp
import asyncio
import json
from bs4 import BeautifulSoup
from tqdm.asyncio import tqdm

# Function to extract abstract and title from URL asynchronously
async def extract_data_from_url(session, url):
    try:
        async with session.get(url) as response:
            html = await response.text()
            soup = BeautifulSoup(html, 'html.parser')
            abstract_section = soup.find('div', class_='abstract-content')
            abstract = abstract_section.get_text(separator='\n').strip() if abstract_section else "Abstract not available"
            title_tag = soup.find('title')
            title = title_tag.text if title_tag else "Title not found"
            return title, abstract
    except aiohttp.ClientConnectorError:
        return "Connection Error", ""
    except aiohttp.ServerDisconnectedError:
        return "Server Disconnected Error", ""

# Load Yesno_11.json file
with open('Yesno_11.json', 'r', encoding='utf-8') as json_file:
    data = json.load(json_file)

# Load BioASQ_11B_test_yesno.json file if it exists
try:
    with open('Retrieved_BioAsq_train.json', 'r', encoding='utf-8') as retrieved_file:
        retrieved_data = json.load(retrieved_file)
except FileNotFoundError:
    retrieved_data = []

# Initialize set to store retrieved URLs
retrieved_urls = set(entry['url'] for entry in retrieved_data)

async def main():
    async with aiohttp.ClientSession() as session:
        for question in tqdm(data, desc="Processing documents"):
            document_urls = question['documents']
            tasks = []
            for url in document_urls:
                if url not in retrieved_urls:  # Check if URL is not retrieved yet
                    tasks.append(extract_data_from_url(session, url))
            results = await asyncio.gather(*tasks)
            for url, (title, abstract) in zip(document_urls, results):
                if url not in retrieved_urls:  # Check if URL is not retrieved yet
                    retrieved_data.append({
                        'url': url,
                        'title': title,
                        'abstract': abstract
                    })
                    retrieved_urls.add(url)


# Get the event loop
loop = asyncio.get_event_loop()

# Run the asynchronous main function
await main()

# Save retrieved data to BioASQ_11B_test_yesno.json file
with open('BioASQ_11B_test_yesno.json', 'w', encoding='utf-8') as output_file:
    json.dump(retrieved_data, output_file, indent=4, ensure_ascii=False)

print("Retrieved data saved to BioASQ_11B_test_yesno.json")